name: Lint po/pot files

on:
  push:
    paths:
      - '**.pot'
      - '**.po'
  workflow_dispatch:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Install Dennis
      - run: pip3 install dennis

      - name: Lint gettext files
      - run: dennis-cmd lint . 
