name: Move files from Weblate
on:
  pull_request:
    types: [ closed ]
    branches: ["main" ]
    paths:
      - '**.po'
  workflow_dispatch:
  
jobs:
  move:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: github.event.pull_request.merged == true

      - name: Move files to their proper folders
        run:  mv ./*.po Meower-Svelte/po

      - name: Commit and push
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "fix: move `po` files to `Meower-Svelte/po`"
